In [1]:
import numpy as np

In [2]:
#Zero Dimensional array
a = np.array(42)
print(a)

42


In [3]:
a = np.array(42)
print(type(a))

<class 'numpy.ndarray'>


In [4]:
#One Dimensional array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [6]:
#Two Dimensional array
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [16]:
#Three Dimensional array
a = np.array([[[1,2,3,4],[5,6,7,8],[1,2,4,3]]])
print(a)

[[[1 2 3 4]
  [5 6 7 8]
  [1 2 4 3]]]


In [17]:
#to check the no.of dimensions.
a = np.array([[1,2,3,4],[5,6,7,8],[1,2,4,3]])
print(a.ndim)

2


In [19]:
a = np.array([[[1,2,4,3]]])
print(a.ndim)
print(a)

3
[[[1 2 4 3]]]


In [24]:
#N Dimensional array
a = np.array([[[1,2,3,4],[5,6,7,8],[1,2,4,3]]],ndmin=7)
print(a)

[[[[[[[1 2 3 4]
      [5 6 7 8]
      [1 2 4 3]]]]]]]


In [25]:
#One Dimensional array Indexing
a = np.array([1,2,3,4,5])
print(a[4])

5


#Two Dimensional array Indexing
##[[1,2,3,4],[5,6,7,8]]
here [1,2,3,4] -> 0

and  [5,6,7,8] -> 1

In [30]:
#Two Dimensional array Indexing
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a[0,2])

3


In [31]:
#Two Dimensional array Indexing
a = np.array([[1,2,3,4],[5,6,7,8],[3,7,8,2]])
print(a[2,3])
print(a[1,1])
print(a[2,2])


2
6
8


#Three Dimensional array Indexing
##[[1,2,3,4],[5,6,7,8][3,7,8,2]]
here,

[[1,2,3,4],[5,6,7,8][3,7,8,2]] -> 0

and

 [1,2,3,4] -> 0

 [5,6,7,8] -> 1

 [3,7,8,2] -> 2

 and

  [1,5,3] -> 0

  [2,6,7] -> 1 ,.. so on


In [34]:
#Three Dimensional array Indexing
a = np.array([[[1,2,3,4],[5,6,7,8],[3,7,8,2]]])
print(a[0,1,2])

7


In [36]:
#Three Dimensional array Indexing by two Arrays
a = np.array([[[1,2,3,4],[5,6,7,8]],[[3,7,8,2],[2,6,8,9]]])
print(a)

[[[1 2 3 4]
  [5 6 7 8]]

 [[3 7 8 2]
  [2 6 8 9]]]


In [37]:
#Three Dimensional array Indexing by two Arrays
a = np.array([[[1,2,3,4],[5,6,7,8]],[[3,7,8,2],[2,6,8,9]]])
print(a[1,1,1])

6


In [38]:
#Three Dimensional array Indexing by three Arrays
a = np.array([[[1,2,3,4],[5,6,7,8]],[[3,7,8,2],[2,6,8,9]],[[1,2,3,4],[5,6,7,8]]])
print(a)

[[[1 2 3 4]
  [5 6 7 8]]

 [[3 7 8 2]
  [2 6 8 9]]

 [[1 2 3 4]
  [5 6 7 8]]]


In [39]:
#Three Dimensional array Indexing by three Arrays
a = np.array([[[1,2,3,4],[5,6,7,8]],[[3,7,8,2],[2,6,8,9]],[[1,2,3,4],[5,6,7,8]]])
print(a[1,1,1])
print(a[2,1,3])
print(a[0,0,3])
print(a[2,0,2])

6
8
4
3


In [40]:
#One Dimensional array slicing
a = np.array([1,2,3,4,5])
print(a[1:4])

[2 3 4]


#One Dimensional array slicing
a = np.array([1,2,3,4,5])

print(a[1:4:2])

here,

1 -> Starting value

4 -> Ending value

2 -> Step value

In [41]:
#One Dimensional array slicing
a = np.array([1,2,3,4,5])
print(a[1:4:2])

[2 4]


#Two Dimensional array slicing
##a[rowStart : rowEnd : rowStep , colStart : colEnd : colStep]
a = np.array([[1,2,3,4,5],[6,5,4,3,2]])

print(a[1:4:2,1:2:2])

1 -> rowStart

4 -> rowEnd - 1

2 -> Step

1 -> colStart

2 -> colEnd - 1

2 -> step


In [43]:
#Two Dimensional array slicing
a = np.array([[1,2,3,4,5],[6,5,4,3,2]])
print(a[1:4:2,1:2:2])

[[5]]


In [53]:
#Two Dimensional array slicing
a = np.array([[1,2,3,4,5],[6,5,4,3,2]])
print(a[1::2,:3:2])

[[6 4]]


In [55]:
#Two Dimensional array slicing (i.e,Positive Slicing)
a = np.array([[1,9,5,7,9],[2,9,4,11,34],[3,9,2,8,7],[2,9,5,3,6],[9,3,5,7,2]])
print(a[0:4:2,:5:2])

[[1 5 9]
 [3 2 7]]


In [58]:
#Two Dimensional array slicing (i.e,Negative Slicing)
a = np.array([[1,9,5,7,9],[2,9,4,11,34],[3,9,2,8,7],[2,9,5,3,6],[9,3,5,7,2]])
print(a[-2:,:-1])

[[2 9 5 3]
 [9 3 5 7]]


In [59]:
#Shapes of an array
a = np.array([[1,9,5,7,9],[2,9,4,11,34],[3,9,2,8,7],[2,9,5,3,6],[9,3,5,7,2]])
print(a.shape)

(5, 5)


In [62]:
#ReShape of an array
a = np.array([[1,2,3,4,5,6,7,8,9]])
print(a.reshape(3,3))
#3 * 3 = 9 is possible
#a = np.array([[1,2,3,4,5,6,7,8,9,0,1,2]])
#4 * 3 = 12 it is possible

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [64]:
#ReShape of an array
a = np.array([[1,2,3,4,5,6,7,8,9,0,1,2]])
print(a.reshape(4,3,1))

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]

 [[0]
  [1]
  [2]]]


In [75]:
#Iterate a Two dimensional array
a = np.array([[1,2,3,4,5,6],[7,8,9,0,1,2]])
for i in a:
  for j in i:
    print(j)

1
2
3
4
5
6
7
8
9
0
1
2


In [78]:
#Iterate a Three dimensional array
a = np.array([[[1,2,3,4,5,6],[7,8,9,0,1,2],[1,2,3,4,5,6]]])
for i in a:
  for j in i:
    for k in j:
      print(k)

1
2
3
4
5
6
7
8
9
0
1
2
1
2
3
4
5
6


In [79]:
#Iterate a n dimensional array
a = np.array([[[1,2,3,4,5,6],[7,8,9,0,1,2],[1,2,3,4,5,6]]])
for x in np.nditer(a):
  print(x)

1
2
3
4
5
6
7
8
9
0
1
2
1
2
3
4
5
6


In [81]:
#enumerate a n dimensional array
a = np.array([[[1,2,3,4,5,6],[7,8,9,0,1,2],[1,2,3,4,5,6]]])
for i,x in np.ndenumerate(a):
  print(i,x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 0, 4) 5
(0, 0, 5) 6
(0, 1, 0) 7
(0, 1, 1) 8
(0, 1, 2) 9
(0, 1, 3) 0
(0, 1, 4) 1
(0, 1, 5) 2
(0, 2, 0) 1
(0, 2, 1) 2
(0, 2, 2) 3
(0, 2, 3) 4
(0, 2, 4) 5
(0, 2, 5) 6


In [83]:
# Concatenate means adding of two arrays
a = np.array([1,2,3])
b = np.array([4,5,6])
p = np.concatenate((a,b))
print(p)

[1 2 3 4 5 6]


In [84]:
# Spliting the array
a = np.array([1,2,3,4,5,6,7,8])
p = np.array_split(a,3)
print(p)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [86]:
# finding the value in array using "where"
a = np.array([1,2,3,4,5,6,7,8])
print(np.where(a==8))

(array([7]),)


In [87]:
# Array Sorting
a = np.array([1,2,6,5,4,3,7,8])
print(np.sort(a))

[1 2 3 4 5 6 7 8]


In [108]:
from numpy import random

In [99]:
x = random.randint(1, 6)
print(x)

2


In [110]:
x = random.rand()
print(x)

0.9047924968058366


In [111]:
x = random.rand(5)
print(x)

[0.59582945 0.64152701 0.17334701 0.64766775 0.43271135]


In [112]:
# uniform creates the floating point between numbers.
x = random.uniform(1,5)
print(x)

3.069172485440672


In [118]:
x = random.choice([5,3,2,1,6,4,9,8,7])
print(x)

2
